# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: "Gileno Filho"
subtitle: "Programação, Python, Django, Web, Inteligência Artificial, Engenharia de Avaliações, Ensino e Minimalismo. Recife, Brasil"
email: contato@gilenofilho.com.br
name: Gileno Filho
description: Website e blog de Gileno Filho
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.gilenofilho.com.br"
cover: "assets/foto-bairrorecife.jpg"
logo:
timezone: America/Recife

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page/:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/categoria/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: gilenofilho

# Google analytics
ga_tracking_id: "UA-15015773-2"

# Category descriptions (for archive pages)
descriptions:
  - cat: cursos
    desc: "Artigos sobre cursos que participei."

  - cat: palestras
    desc: "Artigos sobre palestras que participei."

  - cat: tutoriais
    desc: "Artigos em formato de tutoriais."

  - cat: utils
    desc: "Pacote utils do blog."

social:
  - name: Twitter
    icon: twitter
    username: GilenoFilho
    url: https://twitter.com/gilenofilho
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: gileno
    url: https://github.com/gileno
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Gileno Filho
    url: https://br.linkedin.com/in/gilenofilho
    desc: Connect with me on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username: Gileno Filho
    url: https://www.youtube.com/channel/UCThem2-TpI1kJoNqf_hFZOQ
    desc: Subscribe on YouTube
    share: false

#Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/eu2-thumb.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/eu2-thumb.png"

    os_repo:
    os_rcs_type:
    os_src:
